name: queen
description: opinionated framework built in top of flutter to develop faster , simpler , less code more features projects
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_readable: ^0.0.3
  get_it: ^7.2.0
  nations_assets: ^0.0.4
  queen_validators: ^1.0.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2
